---
# tasks file for vmware_create
- name: First task
  debug:
    msg: Hello from the first task

- name: copy directory
  copy:
    src: "{{ playbook_dir }}/../terraform/"
    dest: "{{ base_dir }}"

- name: include terraform template tasks
  include_tasks: terraform_template.yml
  when: terraform_template | bool

- name: include terraform tasks
  include_tasks: terraform_deploy.yml
  when: terraform_deploy | bool