---
- name: Create folder for new host
  file:
    path: "~/terraform/{{ server_name }}"
    state: directory
    mode: '0755'

- name: Copy template into new folder
  template:
    src: terraform.tf.j2
    dest: "~/terraform/{{ server_name }}/{{ server_name }}.tf"
