---
- name: -- DEPLOY VM TERRAFORM --
  terraform:
    project_path: "{{ base_dir }}/gso-deploy/{{ server_name }}"
    state: present
    force_init: true
  environment:
    VSPHERE_SERVER: "{{ vsphere_server }}"
    VSPHERE_USER: "{{ vsphere_user }}"
    VSPHERE_PASSWORD: "{{ vsphere_password }}"